language: c
sudo: false
script:
- bash -ex scripts/deploy.sh
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_b5c324371014_key -iv $encrypted_b5c324371014_iv -in .deploy_git_env.enc -out deploy_git_delve -d
